# Generated by Django 4.0.4 on 2022-05-01 10:39

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birth_date', birthday.fields.BirthdayField()),
                ('department', models.CharField(choices=[('Personal', 'Personal'), ('Sales', 'Sales'), ('Development', 'Development')], max_length=255)),
            ],
        ),
    ]
